# Generated by Django 3.1.7 on 2021-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210625_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additiondetail',
            name='indent_mark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='additiondetail',
            name='is_address_same',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='additiondetail',
            name='is_disability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='additiondetail',
            name='type_disability',
            field=models.IntegerField(blank=True, choices=[(1, 'Vision Impairment'), (2, 'Deaf or hard of hearing'), (3, 'Mental health conditions'), (4, 'Intellectual disability'), (5, 'Acquired brain injury'), (6, 'Autism spectrum disorder'), (7, 'Physical disability')], default=0, null=True),
        ),
    ]
