# Generated by Django 3.1.7 on 2021-10-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210829_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-not_date']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-upload_date']},
        ),
    ]
